# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Axis_config = debug
  Sandbox_config = debug
endif
ifeq ($(config),release)
  Axis_config = release
  Sandbox_config = release
endif
ifeq ($(config),dist)
  Axis_config = dist
  Sandbox_config = dist
endif

PROJECTS := Axis Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Axis:
ifneq (,$(Axis_config))
	@echo "==== Building Axis ($(Axis_config)) ===="
	@${MAKE} --no-print-directory -C Axis -f Makefile config=$(Axis_config)
endif

Sandbox: Axis
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Axis -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Axis"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"